name: macOS CI

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1

        # brew install libomp open-mpi python@3.9 wget ninja qt@5 libgit2

        # GHA macOS: unpin CMake to fix Homebrew conflict (actions/runner-images#12912)
        brew uninstall --force cmake || true
        # brew untap local/pinned || true
        brew install libomp open-mpi python@3.9 wget cmake ninja qt@5 libgit2 zlib ncurses


        wget https://cmake.org/files/v3.24/cmake-3.24.1-macos-universal.tar.gz
        tar -xzf cmake-3.24.1-macos-universal.tar.gz
        sudo mv cmake-3.24.1-macos-universal/CMake.app /Applications/
        sudo ln -sf /Applications/CMake.app/Contents/bin/cmake /usr/local/bin/cmake

    # - name: Install zlib
    #   run: brew install zlib zstd ncurses

    # - name: Set zlib env vars
    #   run: |
    #     echo "LDFLAGS=-L/opt/homebrew/opt/zlib/lib" >> $GITHUB_ENV
    #     echo "CPPFLAGS=-I/opt/homebrew/opt/zlib/include" >> $GITHUB_ENV
    #     echo "DYLD_LIBRARY_PATH=/opt/homebrew/opt/zlib/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    #     export DYLD_LIBRARY_PATH="/opt/homebrew/opt/zlib/lib:$DYLD_LIBRARY_PATH"
    #     echo "DYLD_LIBRARY_PATH=/opt/homebrew/opt/zstd/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        
    # - name: Symlink ncurses for compatibility
    #   run: |
    #     sudo mkdir -p /opt/local/lib
    #     sudo ln -sf /opt/homebrew/opt/ncurses/lib/libncurses.6.dylib /opt/local/lib/libncurses.6.dylib



    - name: Checkout BioDynaMo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # - name: Cache Third Party Packages
    #   uses: actions/cache@v4
    #   with:
    #     path: build/third_party
    #     key: ${{ runner.os }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}

    - name: Build BioDynaMo
      shell: bash
      run: |
        # export PV_USE_OFFSCREEN=1
        # export QT_QPA_PLATFORM=offscreen
        # export DISPLAY=:0
        cmake -G Ninja \
          -Dopencl=OFF \
          -Dparaview=ON \
          -Dbenchmark=ON \
          -Dlibgit2=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -B build
        cmake --build build --parallel --config Release

    - name: Unit tests BioDynaMo
      shell: bash
      working-directory: build
      run: |
        # export PV_USE_OFFSCREEN=1
        # export QT_QPA_PLATFORM=offscreen
        # export DISPLAY=:0
        . bin/thisbdm.sh
        root --version
        root -config
        bdm config
        ninja run-unit-tests
